name: O que você tentou?
description: "Um pouco sobre como ajudar para ser ajudadado."
meta_description: "Um pouco sobre como ajudar para ser ajudadado."
brand: OQVT?
encoding: UTF-8
markdown: redcarpet
redcarpet:
  extensions: ['smart']
logo: false
paginate: 15

url:            'http://schleumer.github.io/oquevocetentou/'
author:         'A.P.D.A'

links:
  - url: 'https://www.facebook.com/groups/osadpa'
    label: 'A.P.D.A'
  - url: 'http://forum.energylabs.com.br/'
    label: 'Energy Labs'
